### ISSUE TITLE
Bot responds with "Unknown command! (see .help)" when given ".ping" command.

### ISSUE THREAD

**Issue by S-573** [sKiLdUsT/awesomebot#1]
The ping command seems to have been broken after an update, says it should be available to all permissions but it no longer replies with "Pong!"

This obviously isn't at the top of the list of "bugs to be fixed" but it's definitely a bug.

**Comment by sKiLdUsT** [comment]
This is poorly documented at the moment for which I apologize. If you look into the codebase, you would see that the commands have been grouped into modules which now provide commands to the running bot instance depending on which modules have been enabled in you guild. The bot not responding to the "ping" command would be because of the "debug" module not being enabled in you guild, which you can fix with `addModule debug`.

Since this is not a actual bug, I will close this issue now.
